apiVersion: v1
kind: pod
metadata:
  name: taint
  labels:
    purpose: taint-demo
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
